### ISSUE TITLE
First option always focus 

### ISSUE THREAD

**Issue by fenn1ks** [TotomInc/vue3-select-component#103]
![image](https://github.com/user-attachments/assets/c307ee8b-44d6-4121-9233-689b6ffdedd9)

https://vue3-select-component.vercel.app/demo/single-select.html

**Comment by fenn1ks** [comment]
And maybe need add to doc, tree of all classes which are used

**Comment by TotomInc** [comment]
Hi, thanks for opening this issue. It doesn't seem ti be an issue that the first option is focused when the menu is opened.

Could you please clarify what you are trying to achieve?

**Comment by TotomInc** [comment]
Closed because no repro and lack of details. Feel free to reopen with precise bug report and code repro, thanks.

**Comment by funkysoul** [comment]
actually i noticed that too.. i worked around it with styling.. but yeh the first item is always active

**Comment by TotomInc** [comment]
What was the behaviour wanted in your case @funkysoul? When opening the menu, there shouldn't have an option active? What about the first keyboard interaction (e.g. arrow down)?

Would love a bit more feedback on this one, maybe I can add a prop to disable autofocus option on menu open.

**Comment by funkysoul** [comment]
Exactly.. when initially opening the select no option is selected/marked.
If an option was selected and the user closed the select or the focus went off than it should stay selected when reopening.

Sure when the user pushes the key down, then the first item should be focused, if he presses up then it should go the last item.

**Comment by TotomInc** [comment]
Added [`shouldAutofocusOption` prop](https://vue3-select-component.vercel.app/props.html#shouldautofocusoption) on v0.7.0
