### ISSUE TITLE
How to get in v-model two parametrs  label and value {label: label, value: value} 

### ISSUE THREAD

**Issue by fenn1ks** [TotomInc/vue3-select-component#104]
How to get in v-model two parameters  label and value {label: label, value: value} 
because in vue-select-component can get two parameters

**Comment by TotomInc** [comment]
Hi, this is not a recommended pattern. However, this was already resolved by this comment: https://github.com/TotomInc/vue3-select-component/issues/7#issuecomment-2083422621

Assuming each option has a unique value, you can create a computed value to get the active option with all your properties.
