### ISSUE TITLE
Faulty click area with extended padding

### ISSUE THREAD

**Issue by AdrianFahrbach** [TotomInc/vue3-select-component#111]
The padding of the field is currently applied to the parent of the input element.
This means that with increased padding, only the inner part of the field (which is the actual input element) is clickable.

In the screenshot below I increased the padding slightly and only approximately the blue area is clickable:

<img width="343" alt="CleanShot 2024-08-30 at 21 23 45@2x" src="https://github.com/user-attachments/assets/fc6a2eba-a433-49fb-ae27-0566cf8c87dc">

**Comment by TotomInc** [comment]
I'll try to work on this one, but it requires a lot of changes in the structure of the DOM and potentially the styles too (and CSS variables).

It takes a bit of time to do it right, without introducing a lot of breaking changes 😅

**Comment by AdrianFahrbach** [comment]
I guess an easy solution could be negative margin width padding on the input?
Not quite sure, but maybe that works without major changes to the DOM.

**Comment by TotomInc** [comment]
I believe I've found a great workaround without shaking the entire DOM structure. It introduce a new CSS variable too.
If you have some time to test the PR locally, that would be awesome (clone repo w/ correct branch, `npm i` and run `npm run dev:playground`) 🙏

**Comment by AdrianFahrbach** [comment]
I will try to take a look at it on the weekend!
Thank you for adjusting this!

**Comment by TotomInc** [comment]
Released on v0.6.0
