### ISSUE TITLE
Filter menu only update when closing the virtual keyboard on Samsung S23 (Android) + Chrome

### ISSUE THREAD

**Issue by mvkardashin** [TotomInc/vue3-select-component#112]
Hi. Thanks for this awesome library, but I've encountered the following issue.

I'm using a Samsung S23 and Chrome. I enter text to filter the options, but the options update only when I close the virtual keyboard.
I use "vue3-select-component": "^0.5.2",

This is my component:
```
<VueSelect v-model="selectedCity" :options="[

      { label: 'repetitors', value: 'repetitors', code: 'repetitors', id: 1, region: 'Московская область' },
      { label: 'peterburg', value: 'peterburg', code: 'peterburg', id: 2, region: 'Ленинградская область ' },
      { label: 'novosibirsk', value: 'novosibirsk', code: 'novosibirsk', id: 3, region: 'Новосибирская область' },
      { label: 'ekaterinburg', value: 'ekaterinburg', code: 'ekaterinburg', id: 4, region: 'Свердловская область' },
      { label: 'kazan', value: 'kazan', code: 'kazan', id: 5, region: 'республика Татарстан' },
      { label: 'nizhnii-novgorod', value: 'nizhnii-novgorod', code: 'nizhnii-novgorod', id: 6, region: 'Нижегородская область' },
      { label: 'samara', value: 'samara', code: 'samara', id: 7, region: 'Самарская область' },
      { label: 'chelyabinsk', value: 'chelyabinsk', code: 'chelyabinsk', id: 8, region: 'Челябинская область' },
      { label: 'omsk', value: 'omsk', code: 'omsk', id: 9, region: 'Омская область' },
      { label: 'rostov-na-donu', value: 'rostov-na-donu', code: 'rostov-na-donu', id: 10, region: 'Ростовская область' },
      { label: 'ufa', value: 'ufa', code: 'ufa', id: 11, region: 'республика Башкортостан' }
    ]" @option-selected="onSelectCity" :isClearable="false" placeholder="Выберите город">
```
Example on video: https://mvkardashin.github.io/selest3/index.html

https://github.com/user-attachments/assets/dcb8dc43-5398-4fde-8c91-f7dd09b49f79

**Comment by TotomInc** [comment]
Thanks for the issue. However, I am not able to reproduce the issue as it seems to be specific on Chrome Android and I don't own an Android device. I wasn't able to reproduce it on macOS Chrome, iOS Safari and Windows 11 Chrome, unfortunately.

I've also reviewed the code linked to the input `v-model` but haven't been able to find anything that could cause the issue. 😕

@mvkardashin do you have some time to do a bit of research? You can clone the vue3-select-component repository, run `npm install` and run `npm run dev:playground` to run a development environment of the vue3-select-component. Then, you could connect your Samsung S23 on your computer and debug remotely your S23 on Chrome, [as explained here by Google](https://developer.chrome.com/docs/devtools/remote-debugging).

Any error message could help the investigation! 🙏

**Comment by TotomInc** [comment]
Alright, that's fine! Enjoy the component! 🙂

**Comment by mvkardashin** [comment]
> Alright, that's fine! Enjoy the component! 🙂

@TotomInc  Unfortunately, I find yesterday 4 phones with such problem. All devices on android. I connect my phone to Chrome Developer by adb, and couldn't find anything. 

But interesting thing: on my samsung i use default Samsung keyboard. Now i install Google Keyboard, and problem dissapear. But I can't tell users on my site, that they need to install additional keyboard)

**Comment by mvkardashin** [comment]
@TotomInc 
It seems, I find solution:
Your code for input below
```
 <input
          :id="inputId"
          ref="input"
          v-model="search"
          class="search-input"
          type="text"
          aria-autocomplete="list"
          autocapitalize="none"
          autocomplete="off"
          autocorrect="off"
          spellcheck="false"
          tabindex="0"
          :disabled="isDisabled"
          :placeholder="selectedOptions.length === 0 ? placeholder : ''"
          @mousedown="openMenu()"
          @keydown="handleInputKeydown"
        >
```

But you need add @input event. Example of usage: 
`<input :value="text" @input="event => text = event.target.value">`

It need, because @input event occurs immediately after the value of an element has changed. I try on my test page and it works with samsung keyboard.

I hope you can fix it)
