### ISSUE TITLE
Add a loading animation

### ISSUE THREAD

**Issue by JLEGit** [TotomInc/vue3-select-component#122]
While the select data is being loaded, run a loading animation on the select

**Comment by TotomInc** [comment]
I've added an `isLoading` prop which toggles a loading animation that can also be overwritten using the `loading` slot.

I've also introduced 2 new CSS variables for the spinner.

Published under v0.6.1 🎈 

- https://vue3-select-component.vercel.app/props.html#isloading
- https://vue3-select-component.vercel.app/slots.html#loading
- https://vue3-select-component.vercel.app/styling.html
