### ISSUE TITLE
Dynamically fetching & loading options when options prop isn't defined

### ISSUE THREAD

**Issue by JLEGit** [TotomInc/vue3-select-component#125]
First of all, thanks for the loading spinner, much appreciated.

Just a small issue, basically, on a projet, we load datas for the select dynamically and an issue happend, when no option is in the Select (because it's currently on loading phase), an error happend : **TypeError: Cannot read properties of null (reading 'find')**

**Comment by TotomInc** [comment]
Closing as there's no update and I believe this is a user error because the options prop isn't an array.
