### ISSUE TITLE
Allow a custom option slot for #value when `isMulti` is set

### ISSUE THREAD

**Issue by rudokemper** [TotomInc/vue3-select-component#128]
As far as I can tell, a [custom option slot](https://vue3-select-component.vercel.app/demo/custom-option-slot.html) for `#value` does not render anything when `isMulti` is true. That is to say, the following code will not template selected options any differently:

```
<VueSelect
  :is-multi="true"
  :options="options"
  v-model="values"
>
  <template #value="{ option }">
    {{ option.label }} (selected)
  </template>
  <template #option="{ option }">
    {{ option.label }}
  </template>
</VueSelect>
```

It would be nice to have this. [`vue-select`](https://github.com/sagalbot/vue-select) permitted this with the `v-slot:selected-option` parameter, which I used to style my multiple select dropdowns like this:

![image](https://github.com/user-attachments/assets/3c3f706a-e408-493d-ac65-23bd9399a4fb)

If you agree that this is a nice feature to have, I can take a shot at adding this, unless you prefer to take it on :slightly_smiling_face:

**Comment by TotomInc** [comment]
That's a nice catch @rudokemper, you're right [the `#value` slot isn't used when `:is-multi="true"`](https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L395-L403).

I believe we can introduce a new slot called `#tag`. This new slot [should replace these lines](https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L406-L414). It should also allow access to the following values:
- `option`: the option object of the tag
- `removeOption()`: function to remove the tag from the selected values

If you have some time to work on this, a merge-request would be awesome 🙏 

Feel free to also work on the Vitepress documentation if you have the time.

Thanks!

**Comment by TotomInc** [comment]
Added in v0.7.0: https://vue3-select-component.vercel.app/slots.html#tag

Thanks for your help! 🙂
