### ISSUE TITLE
Menu doesn't close when clicking on dropdown icon

### ISSUE THREAD

**Issue by neo-reply-kevin** [TotomInc/vue3-select-component#131]
Hi, I'm rendering a chevron icon into my VueSelect component like this:

```vue
<template #dropdown>
    <IconChevron class="h-full w-full" />
</template>
```

I expect the Select-Component to close when I click on the chevron while the dropdown is open. Unfortunately, there is no API for such a feature. It would be great add this in the future.

Recording of what i mean:
https://github.com/user-attachments/assets/320e365d-1591-496a-bd74-ab51d4155705

Best,
Kevin

**Comment by TotomInc** [comment]
The dropdown slot is wrapped inside a button that has an `@click="openMenu"`: https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L172-L179

I think adding a `toggleMenu` function and binding this function to the button should make it work.

What do you think @neo-reply-kevin?

**Comment by TotomInc** [comment]
Fixed on v0.7.0

**Comment by neo-reply-kevin** [comment]
That did the job, and on top of that, it was really fast. Thanks much! Where's your buy-me-a-coffee link? ☕

**Comment by TotomInc** [comment]
I don't have any, and that's fine. Thanks for considering it! 🙂
