### ISSUE TITLE
Keep search value on blur when no option selected

### ISSUE THREAD

**Issue by NicholasLoren** [TotomInc/vue3-select-component#132]
Can the Select component get a reduce attribute which allows it to properly reduce options to the label and value format
Also, I want to customize it in a way that the search value is not cleared when the option is not in the list, I am working on a project that can allow the value to be created as a new entry on save.

**Comment by TotomInc** [comment]
> Can the Select component get a reduce attribute which allows it to properly reduce options to the label and value format

Not sure I've understood correctly. If you want to change the displayed value in the dropdown list, use [`getOptionLabel`](https://vue3-select-component.vercel.app/props.html#getoptionlabel) prop. 

> Also, I want to customize it in a way that the search value is not cleared when the option is not in the list, I am working on a project that can allow the value to be created as a new entry on save.

I'm not sure what is this use-case is for, there's no real UX improvement by keeping the search value inserted if there's no value selected/found.
