### ISSUE TITLE
[bug?] example code shows a warning

### ISSUE THREAD

**Issue by sevillaarvin** [TotomInc/vue3-select-component#4]
Hi, I created a template vue3 project (https://github.com/cyberaesthete/example-vue3-select-component) and followed the getting started instructions (https://vue3-select-component.vercel.app/getting-started.html).

However, the sample code will show an error:

```text
main.js:6 [Vue warn]: Invalid prop: custom validator check failed for prop "modelValue". 
  at <Select modelValue=null onUpdate:modelValue=fn options= (3) [{…}, {…}, {…}]  ... > 
  at <HelloWorld msg="You did it!" > 
  at <App>
```

Project creation commands for reference (all I did was replace HelloWorld.vue with the sample code):

```sh
npm create vue@latest
cd vue-project/
npm install

npm add -D vue3-select-component
vim src/components/HelloWorld.vue
npm run dev
```

**Comment by TotomInc** [comment]
Hey, thanks for reporting this. I've tried to reproduce the issue without success.

By the sample code, are you talking about the example in the README, on the ["Installation" section](https://github.com/TotomInc/vue3-select-component?tab=readme-ov-file#installation)?

**Comment by sevillaarvin** [comment]
I used this https://vue3-select-component.vercel.app/getting-started.html#usage:

```vue
<script setup lang="ts">
import "vue3-select-component/dist/style.css";

import { ref } from "vue";
import VueSelect from "vue3-select-component";

const selected = ref<string | null>(null);
</script>

<template>
  <VueSelect
    v-model="selected"
    :options="[
      { label: 'Option #1', value: 'option_1' },
      { label: 'Option #2', value: 'option_2' },
      { label: 'Option #3', value: 'option_3' },
    ]"
    placeholder="Select an option"
  />
</template>
```

I see. Perhaps it only shows on MacOS. Tested both on Safari and Chrome:

<details>
<summary>
Safari
</summary>
![image](https://github.com/TotomInc/vue3-select-component/assets/33614172/c091ddf5-2b84-4856-ac51-3f4fc4cd7277)
</details>

<details>
<summary>
Chrome
</summary>
![image](https://github.com/TotomInc/vue3-select-component/assets/33614172/29224ebf-0dc1-4283-a1de-462111657803)

</details>

**Comment by TotomInc** [comment]
I've just pushed a fix on the documentation, there were indeed a typo. It shouldn't be `null` but an empty string `""`.

Thanks for reporting this!

**Comment by sevillaarvin** [comment]
By the way is there a reason why only strings are allowed?

I was hoping for something like this, where the label is the user's name and the value is a numeric database id:

```js
const users = [
    { label: 'Alpha', value: 5 },
    { label: 'Bravo', value: 42 },
    { label: 'Charlie', value: 123 },
]
```

**Comment by sevillaarvin** [comment]
Something like this maybe? 

https://github.com/schtappe/vue3-select-component/commit/77cf1714d2b8a2c3e38901a4a887d4ee8282ff2c

**Comment by TotomInc** [comment]
I actually think this could be possible thanks to the [recent addition of "Generics" in Vue 3.3](https://vuejs.org/api/sfc-script-setup.html#generics).

I'll open another issue which references your comment to track the work done.
