### ISSUE TITLE
slot for options and filters

### ISSUE THREAD

**Issue by foxhound87** [TotomInc/vue3-select-component#67]
Hello, 
It would be nice to have a slot when you open the dropdown, 
before the list of options that can be set as absolute.

I have attached a screenshot of what I'm looking to achieve.
![Schermata 2024-06-21 alle 18 15 14](https://github.com/TotomInc/vue3-select-component/assets/1292494/28237dc9-2b87-41aa-9da3-fdefeff9507d)

**Comment by TotomInc** [comment]
Hi, thanks for reporting this issue.

This one is most likely very tricky.

What are you trying to achieve, a custom filter inside the menu dropdown?

**Comment by foxhound87** [comment]
yes, but just a slot named "options" or "filters" should be enough. 
So I can make the HTML structure for the filters and populate the option from an HTTP call.

**Comment by TotomInc** [comment]
I've added a slot named `#menu-header` which is rendered before the options list.

Here's a demo deployment: https://vue3-select-component-git-feat-m-adcc75-thomas-cazades-projects.vercel.app/demo/with-menu-header.html

I think this should cover a lot of use-cases as this is a very basic slot that anyone can customize and put anything they want.

**Comment by TotomInc** [comment]
Will notice when it's deployed on a new version.

**Comment by TotomInc** [comment]
Available on v0.3.0

cc @foxhound87

**Comment by foxhound87** [comment]
Thank you!
