### ISSUE TITLE
Component seems not emit events

### ISSUE THREAD

**Issue by Iscrimou** [TotomInc/vue3-select-component#7]
I can't get any events from this component, I tried @input, @change and others, but no one returns me anything. How can I get the selected option in moment it's selected to call a method for it?

**Comment by TotomInc** [comment]
As [mentioned here](https://vue3-select-component.vercel.app/events.html), the component doesn't emit any events at the moment.

Could you please elaborate on what you are trying to do?

If you are trying to retrieve the selected option value (`option.value`), you should pass a `ref()` inside the `v-model`.

Using `v-model`, you will receive the `value` property of your option.

Instead, if you want to get the entire option object, this could be done with a `computed` (assuming each `option.value` is unique, which should be):

```ts
import { computed, ref } from "vue";

const userOptions = [
  { label: "Alice", value: 1, username: "alice15" },
  { label: "Bob", value: 2, username: "bob01" },
  { label: "Charlie", value: 3, username: "charlie20" },
];

const selectedValue = ref<number>();
const activeOption = computed(() => userOptions.find((option) => option.value === selectedValue.value));
```

**Comment by Iscrimou** [comment]
> As [mentioned here](https://vue3-select-component.vercel.app/events.html), the component doesn't emit any events at the moment.
> 
> Could you please elaborate on what you are trying to do?
> 
> If you are trying to retrieve the selected option value (`option.value`), you should pass a `ref()` inside the `v-model`.
> 
> Using `v-model`, you will receive the `value` property of your option.
> 
> Instead, if you want to get the entire option object, this could be done with a `computed` (assuming each `option.value` is unique, which should be):
> 
> ```ts
> import { computed, ref } from "vue";
> 
> const userOptions = [
>   { label: "Alice", value: 1, username: "alice15" },
>   { label: "Bob", value: 2, username: "bob01" },
>   { label: "Charlie", value: 3, username: "charlie20" },
> ];
> 
> const selectedValue = ref<number>();
> const activeOption = computed(() => userOptions.find((option) => option.value === selectedValue.value));
> ```

Thanks, it's work for me, but I have to avoid the pattern used in the project.

**Comment by TotomInc** [comment]
Hey @Iscrimou, I've opened a PR to introduce 2 new events (`@option-selected`, `@option-deselected`).

These events can cover edge-cases where relying on the v-model isn't sufficient.
