### ISSUE TITLE
multi select with object is not working.

### ISSUE THREAD

**Issue by ItsNotMyFault** [TotomInc/vue3-select-component#71]
My options are objects, but on initialization I can't define an array of pre-exisitng options their format isn't recogned properly.
code seems to be comparing an object's value with an object.

around these lines:
where l is an object of an array of initial options to be preselected
```
      if (t.isMulti)
        return a.value.map(
          (l) => t.options.find((u) => u.value === l)
        );
```

**Comment by TotomInc** [comment]
If you want to set pre-selected options, you should set the value of your options inside your `v-model`.

Here's a quick example:

```vue
<script setup lang="ts">
import { ref } from "vue";

// "Alice" and "David" will be pre-selected.
const activeUsers = ref<number[]>([1, 4]);

const userOptions: UserOption[] = [
  { label: "Alice", value: 1 },
  { label: "Bob", value: 2 },
  { label: "Charlie", value: 3 },
  { label: "David", value: 4 },
];
</script>

<template>
  <VueSelect
    v-model="activeUsers"
    :options="userOptions"
    :is-multi="true"
    placeholder="Pick users"
  />
</template>
```

I'll add a demo example on the documentation website to make it clear.

**Comment by ItsNotMyFault** [comment]
If you replace your userOptions values with an object it crashes.
Ex: 
` { label: "Alice", value: { username: 'john', lastname: 'doe'} }`

**Comment by TotomInc** [comment]
The value shouldn't be an object but a unique string or number. The value is used to keep track internally of selected options. If you need extra properties, see https://vue3-select-component.vercel.app/dropdown-options.html#passing-extra-properties
