### ISSUE TITLE
do not remove option when disabled

### ISSUE THREAD

**Issue by foxhound87** [TotomInc/vue3-select-component#73]
Hello,
If the component is disabled and I already selected some options, they can be removed (if I click on it).
Is it the correct behavior? I expected the options to be not removable (when the component is disabled).

Thank You

**Comment by TotomInc** [comment]
Hi, thanks for reporting this issue.

I wasn't able to reproduce it but I've noticed a missing statement on the `removeOption()` function.

**Comment by TotomInc** [comment]
Fixed on v0.4.0
