### ISSUE TITLE
automatically remove items from selected when options updated

### ISSUE THREAD

**Issue by foxhound87** [TotomInc/vue3-select-component#75]
Hello,
right now if I have selected some options and I update the options ref and some selected options are not present anymore in the option ref, then the item is displayed without a label and cannot be removed (it throws an error).
The correct behavior should be that the options that are not anymore in the options should be automatically removed from the v-model.

![Schermata 2024-06-25 alle 14 31 21](https://github.com/TotomInc/vue3-select-component/assets/1292494/38d2b79e-18c6-4fa5-bdaf-1822cf6bdd33)

**Comment by foxhound87** [comment]
For this issue, if you are planning to introduce `displayedOptions` maybe we can internally keep also the options that are removed by the filter (instead to remove them). What do you think?

**Comment by TotomInc** [comment]
I believe this issue should be resolved with the new prop `displayedOptions` at #76, and as discussed at #74.

**Comment by TotomInc** [comment]
Should be fixed on v0.4.0, thanks for the `displayedOptions` prop.

See: https://vue3-select-component.vercel.app/props.html#displayedoptions
