### ISSUE TITLE
TypeError when unmounting component

### ISSUE THREAD

**Issue by foxhound87** [TotomInc/vue3-select-component#92]
Hello,
after I unmount the component I get this error:

```
Uncaught (in promise) TypeError: a.value.map is not a function
    at vue3-select-component.js?v=5fca8a25:170:24
    at ReactiveEffect.fn (chunk-MC3FMTAG.js?v=5fca8a25:1241:13)
    at ReactiveEffect.run (chunk-MC3FMTAG.js?v=5fca8a25:427:19)
    at get value (chunk-MC3FMTAG.js?v=5fca8a25:1254:107)
    at Proxy.<anonymous> (vue3-select-component.js?v=5fca8a25:259:29)
    at renderComponentRoot (chunk-CRHHUGQT.js?v=5fca8a25:936:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-CRHHUGQT.js?v=5fca8a25:5156:26)
    at ReactiveEffect.run (chunk-MC3FMTAG.js?v=5fca8a25:427:19)
    at instance.update (chunk-CRHHUGQT.js?v=5fca8a25:5206:17)
    at updateComponent (chunk-CRHHUGQT.js?v=5fca8a25:5022:18)
```

It is also hard to debug since the package is already minified.

**Comment by TotomInc** [comment]
@foxhound87 can you share how are you unmounting the component please? Is it with the `:is-multi="true"` prop?

I believe it is related to the following lines: https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L151-L153

Or it could also come from the `.map` used to set the `:aria-label`: https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L381

**Comment by foxhound87** [comment]
Yes I'm using is-multi prop

the lines from the error are:

```
      if (l.isMulti)
        return a.value.map(
          (t) => l.options.find((p) => p.value === t)
        );
```

and 

```
            "aria-label": y.value.length ? y.value.map(e.isMulti ? e.getMultiValueLabel : e.getOptionLabel).join(", ") : "",
```

**Comment by foxhound87** [comment]
I don't know how to share my code since is a little complex.
My options are not removed (they are computed)

I tested with a check on the options when doing the map:

```

**Comment by foxhound87** [comment]
Sorry I sent the message for mistake before finishing writing , I edited the post with more info.
Please I need this fix!

**Comment by TotomInc** [comment]
I'm not sure the fix belong to the component, as the `v-model` you are passing at the time of error is wrong.

When you're using the component with the `:is-multi="true"` mode, you should ensure the `v-model` type is an array even when no values are selected (`[]`).

In your case, I believe that the ref you are passing as a `v-model` to the component, is at some point `undefined` or `null` after a certain user-interaction, which is not valid for `:is-multi="true"` mode.

Could you please check and ensure the `v-model` passed is valid?

If possible, attach a screenshot or video with Vue devtools showing the `vue3-select-component` states/variables.

Note that there's also a custom `v-model` validator [defined here](https://github.com/TotomInc/vue3-select-component/blob/master/src/Select.vue#L114-L117) that will throw an error on the user-side, if the `v-model` isn't an array when setting `:is-multi="true"`.

**Comment by foxhound87** [comment]
Thank you for your support, 
I think I will revert my changes, because before it was not happening.

**Comment by foxhound87** [comment]
I'm doing more debugging and I can't find a solution to this issue.
Right now the v-model is assigned in a `watch` and it's working.
If I move the assignment to `onMounted` it breaks.
The v-model is valid and this are the component props from the vue devtools:

![Schermata 2024-07-22 alle 11 22 05](https://github.com/user-attachments/assets/bfeb165d-abfb-44cc-8bac-d0292bac6add)

**Comment by foxhound87** [comment]
From the debug:

```
      if (l.isMulti) <--- isMulti is true
        return a.value.map( <--- value is string instead array of string
          (t) => l.options.find((p) => p.value === t)
        );
```

**Comment by foxhound87** [comment]
With more testing could be fixed with:

```
if (l.isMulti && Array.isArray(a.value))
```

please let me know

**Comment by TotomInc** [comment]
@foxhound87 can you please try with the `v0.5.2`? I've pushed a fix to ensure this user-land error doesn't throw anymore (and break the component). It is now gracefully handled, and should return an empty array during the time the `v-model` type is invalid when used with `isMulti`.

Please see the merge-request details for more info.

**Comment by foxhound87** [comment]
Thank you for the release, it seems working now!
